parameters: {}
environment: {}
packages:
    - name: copper
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: copper-enumerator
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          webSecure: "${DO_SECRET}"
          parameters: {}
          environment:
            COPPER_API_KEY: "${COPPER_API_KEY}"
            COPPER_API_USER_EMAIL: "${COPPER_API_USER_EMAIL}"
            DO_SECRET: "${DO_SECRET}"
            COPPER_TARGET_PIPELINE_ID: "${COPPER_TARGET_PIPELINE_ID}"
            COPPER_TARGET_CUSTOM_FIELD_DEFINITION_ID: "${COPPER_TARGET_CUSTOM_FIELD_DEFINITION_ID}"
          annotations: {}
          limits: {}
